apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-default-cert
type: Opaque
data:
  cert.pem: |-
    {{ .Files.Get "certs/cert.pem" | b64enc }}
  key.pem: |-
    {{ .Files.Get "certs/key.pem" | b64enc }}
