{{- if and .Values.tyk-pro.enabled .Values.tib.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tyk-tib-conf
  labels:
    app: tib-{{ include "tyk-chart.fullname" . }}
    chart: {{ include "tyk-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- (.Files.Glob "configs/tib.conf").AsConfig | nindent 2 }}
{{- end }}