{{- if not .Values.secrets.useSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-hybrid.fullname" . }}
  labels:
    app: secrets-data-{{ include "tyk-hybrid.fullname" . }}
    chart: {{ include "tyk-hybrid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  redisPass: "{{ .Values.redis.pass }}"
  rpcKey: "{{ default .Values.tyk_k8s.org_id .Values.gateway.rpc.rpcKey }}"
  apiKey: "{{ default .Values.tyk_k8s.dash_key .Values.gateway.rpc.apiKey }}"
  APISecret: "{{ .Values.secrets.APISecret }}"
{{- end }}
