{{- if .Values.gateway.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mgmt-gateway-conf-{{ include "tyk-pro.fullname" . }}
  labels:
    app: gateway-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  tyk_mgmt.conf: |
    {
      "http_server_options": {
        "certificates": [
        {{- $length := len .Values.gateway.certificates -}}
        {{- range $i, $certset := .Values.gateway.certificates }}
          {
            "cert_file": "/etc/certs/crts/{{ $certset.certFilename }}",
            "key_file": "/etc/certs/keys/{{ $certset.keyFilename }}"
          }{{- if lt $i (sub $length 1) }},{{- end }}
        {{- end }}
        ]
      }
    }
{{- end }}
