{{- if .Values.pump.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pump-conf-{{ include "tyk-pro.fullname" . }}
  labels:
    app: pump-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pump.conf: |
    {}
{{- end }}