{{ if or ( and .Values.gateway.enabled .Values.gateway.tls) ( and .Values.mdcb.enabled .Values.mdcb.tls )}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-default-cert
  labels:
    app: cert-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  cert.pem: |-
    {{ .Files.Get "certs/cert.pem" | b64enc }}
  key.pem: |-
    {{ .Files.Get "certs/key.pem" | b64enc }}
{{ end }}
