apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  redisPass: "{{ .Values.redis.pass }}"
  mongoURL: "{{ include "tyk-pro.mongo_url" . | quote }}"
  AdminSecret: "{{ .Values.secrets.AdminSecret }}"
  APISecret: "{{ .Values.secrets.APISecret }}"
  DashLicense: "{{ .Values.dash.license | quote }}"
  MDCBLicense: "{{ .Values.mdcb.license | quote }}"
  tibSecret: "{{ .Values.tib.secret }}"
