{{- range $key := list "dash" "gateway" "mdcb" "pump" "tib" }}
{{ $deployment := index $.Values $key -}}
{{- if $deployment.mounts }}
{{- range $secret := $deployment.mounts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret-{{ $secret.name }}
  labels:
    app: secret-{{ $secret.name }}-{{ include "tyk-pro.fullname" $ }}
    chart: {{ include "tyk-pro.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
type: Opaque
data:
  {{ $secret.filename }}: |-
{{ $.Files.Get "mounts/$secret.filename" | b64enc | indent 2 }}
{{- end }}
{{- end }}
{{- end }}