apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-conf-{{ include "tyk-headless.fullname" . }}
  labels:
    app: controller-{{ include "tyk-headless.fullname" . }}
    chart: {{ include "tyk-headless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  tyk_k8s.yaml: |-
    Ingress:
      watchNamespaces:
{{ toYaml .Values.tyk_k8s.watchNamespaces | indent 8 }}
    Tyk:
      url: "http{{- if .Values.gateway.tls }}s{{- end }}://localhost:{{ .Values.gateway.api.containerPort }}"
      secret: "set-by-env"
      org: "set-by-env"
      isGateway: true
      insecureSkipVerify: true
    Injector:
      createRoutes: false
