apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  redisPass: "{{ .Values.redis.pass }}"
  mongoURL: "{{ .Values.mongo.mongoURL }}"
  APISecret: "{{ .Values.secrets.APISecret }}"
