name: Release Helm charts

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo: ["tyk-pro", "tyk-headless", "tyk-hybrid"]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.3

      - name: Read Helm Chart version
        id: chart-values
        run: echo "::set-output name=version::$(awk '/version:/ {print $2}' ${{ matrix.repo }}/Chart.yaml)"

      - name: Package Helm Chart
        run: helm package ${{ matrix.repo }} --version ${{ steps.chart-values.outputs.version }}

      - name: Push Helm Chart
        uses: cloudsmith-io/action@v0.5.2
        with:
         api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
         command: "push"
         format: "helm"
         owner: "tyk"
         repo: "helm"
         file: "${{ matrix.repo }}-${{ steps.chart-values.outputs.version }}.tgz"
