name: Smoke test and lint

on:
  pull_request: {}

env:
  TIMEOUT: 3m
  NAMESPACE: tyk-ce
  TYK_CE: .github/tyk_ce_values.yaml

jobs:

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
        with:
          version: v3.3.0
      
      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml


  smoke-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: ["v1.20.2","v1.19.7","v1.18.15","v1.17.17","v1.16.15"]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Create Kind Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          config: .github/kind-cluster-${{ matrix.k8s_version }}.yml
      
      - name: Install helm
        uses: Azure/setup-helm@v1.1
        with:
          version: v3.5.3
      
      - name: Deploy Tyk CE and Dependencies 
        run: |
          kubectl create namespace ${{ env.NAMESPACE }}
          
          # Do not change the name
          helm install mongo simple-mongodb --repo 'https://helm.tyk.io/public/helm/charts/' -n ${{ env.NAMESPACE }} --timeout ${{ env.TIMEOUT }}
          helm install redis simple-redis --repo 'https://helm.tyk.io/public/helm/charts/' -n ${{ env.NAMESPACE }} --timeout ${{ env.TIMEOUT }}

          helm install tyk-ce ./tyk-headless -n ${{ env.NAMESPACE }} --timeout ${{ env.TIMEOUT }}

      - name: Upgrade Tyk CE
        run: |
          helm upgrade -f ${{ env.TYK_CE }} tyk-ce ./tyk-headless -n ${{ env.NAMESPACE }} --timeout ${{ env.TIMEOUT }}

      - name: Uninstall Tyk CE
        run: |
          helm uninstall tyk-ce -n ${{ env.NAMESPACE }} --timeout ${{ env.TIMEOUT }}